[package]
name = "wavetable"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version ="3.0.7", features = ["derive"] }
float-cmp = "0.9.0"
num = "0.4.0"
portmidi = "0.2.5"
sndfile-sys = "0.3.1"
