[package]
name = "wavetable"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
clap = {version ="3.0.7", features = ["derive"] }
cpal = "0.13.4"
float-cmp = "0.9.0"
num = "0.4.0"
portmidi = "0.2.5"
rand = "0.8.5"
rustfft = "6.0.1"
sndfile-sys = "0.3.1"
